###  🧹  EDA Y LIMPIEZA TICKETMASTER

In [42]:
#Cargar archivos
data_ticketmaster = pd.read_csv('eventos_ticketmaster.csv')

In [44]:
#Nº de filas y columnas que componen cada dataset
print(data_ticketmaster.shape)

(510, 21)

In [46]:
data_ticketmaster.head()

,ciudad_buscada,id_evento,nombre,fecha,hora,estado_evento,fecha_venta,url,tipo_evento,genero,...,precio_min,precio_max,promotor,ciudad_real,pais,lugar,direccion,latitud,longitud,codigo_postal
0,Santa Cruz de Tenerife,Z698xZ2qZ1k7EO48b,Fito & Fitipaldis - Aullidos Tour 25/26,2026-03-14,21:30:00,onsale,2025-04-30T08:00:00Z,https://www.ticketmaster.es/event/fito--fitipa...,Music,Rock,...,NaN,NaN,Live Nation España True Vibes SL,Santa Cruz de Tenerife,Spain,Recinto Ferial de Tenerife,"Avenida de la Constitución, 12",28.45504,-16.25666,38005.0
1,Santa Cruz de Tenerife,Z698xZ2qZ16v17GN8Y,MVRK: Pórtate bien!,2025-11-28,21:00:00,onsale,2025-05-14T11:00:00Z,https://www.ticketmaster.es/event/mvrk-portate...,Music,Hip-Hop/Rap,...,NaN,NaN,Polar Nights SL,San Cristóbal de La Laguna,Spain,Aguere Espacio Cultural,"Calle Herradores, 47",28.48762,-16.31690,38204.0
2,Barcelona,Z698xZ2qZ16v78-NOV,Lauren Spencer Smith - THE ART OF BEING A MESS...,2025-09-04,20:30:00,onsale,2025-05-09T07:00:00Z,https://www.ticketmaster.es/event/lauren-spenc...,Music,Rock,...,NaN,NaN,Live Nation España S.A.U.,Barcelona,Spain,Sala Razzmatazz 1,"C. Almogàvers, 122",41.39772,2.19111,8018.0
3,Barcelona,Z698xZ2qZ1kbvG8O_,Lauren Spencer Smith - THE ART OF BEING A MESS...,2025-09-04,20:30:00,offsale,2025-05-09T07:00:00Z,https://www.ticketmaster.es/event/lauren-spenc...,Music,Rock,...,NaN,NaN,Live Nation España S.A.U.,Barcelona,Spain,Sala Razzmatazz 1,"C. Almogàvers, 122",41.39772,2.19111,8018.0
4,Barcelona,Z698xZ2qZ16ee4_o0-,Neo Pistea - Culto Tour Internacional 2025,2025-09-04,21:00:00,onsale,2025-05-21T14:00:00Z,https://www.ticketmaster.es/event/neo-pistea-c...,Music,Hip-Hop/Rap,...,NaN,NaN,Live Nation España S.A.U.,Barcelona,Spain,Sala Apolo,"C. Nou de la Rambla, 113",41.37441,2.16953,8004.0

In [48]:
data_ticketmaster.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ciudad_buscada  510 non-null    object
 1   id_evento       510 non-null    object
 2   nombre          510 non-null    object
 3   fecha           510 non-null    object
 4   hora            456 non-null    object
 5   estado_evento   510 non-null    object
 6   fecha_venta     510 non-null    object
 7   url             510 non-null    object
 8   tipo_evento     510 non-null    object
 9   genero          510 non-null    object
 10  subgenero       510 non-null    object
 11  precio_min      0 non-null      float64
 12  precio_max      0 non-null      float64
 13  promotor        490 non-null    object
 14  ciudad_real     510 non-null    object
 15  pais            510 non-null    object
 16  lugar           510 non-null    object
 17  direccion       504 non-null    object
 18  latitud         472 non-null    float64
 19  longitud        472 non-null    float64
 20  codigo_postal   463 non-null    float64
dtypes: float64(5), object(16)
memory usage: 83.8+ KB

In [50]:
data_ticketmaster.nunique()

ciudad_buscada      8
id_evento         510
nombre            281
fecha             172
hora               22
estado_evento       4
fecha_venta       267
url               509
tipo_evento         4
genero             20
subgenero          23
precio_min          0
precio_max          0
promotor           79
ciudad_real        16
pais                3
lugar              96
direccion          90
latitud            89
longitud           88
codigo_postal      61
dtype: int64

In [52]:
#Eliminar columnas que no voy a usar
data_ticketmaster = data_ticketmaster.drop(columns=['subgenero', 'precio_min', 'precio_max', 'ciudad_real', 'pais'])

In [54]:
# Convertir fechas a datetime
data_ticketmaster['fecha'] = pd.to_datetime(data_ticketmaster['fecha'], errors='coerce')
data_ticketmaster['fecha_venta'] = pd.to_datetime(data_ticketmaster['fecha_venta'], errors='coerce')

In [56]:
# Convertir código postal a entero (manteniendo NaN)
data_ticketmaster['codigo_postal'] = pd.to_numeric(data_ticketmaster['codigo_postal'], errors='coerce').astype('Int64')

In [58]:
#Eliminar eventos cancelados
data_ticketmaster = data_ticketmaster[data_ticketmaster["estado_evento"] != "cancelled"]

In [60]:
data_ticketmaster.info()

<class 'pandas.core.frame.DataFrame'>
Index: 498 entries, 0 to 509
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ciudad_buscada  498 non-null    object
 1   id_evento       498 non-null    object
 2   nombre          498 non-null    object
 3   fecha           498 non-null    datetime64[ns]
 4   hora            453 non-null    object
 5   estado_evento   498 non-null    object
 6   fecha_venta     498 non-null    datetime64[ns, UTC]
 7   url             498 non-null    object
 8   tipo_evento     498 non-null    object
 9   genero          498 non-null    object
 10  promotor        478 non-null    object
 11  lugar           498 non-null    object
 12  direccion       494 non-null    object
 13  latitud         460 non-null    float64
 14  longitud        460 non-null    float64
 15  codigo_postal   451 non-null    Int64
dtypes: Int64(1), datetime64[ns, UTC](1), datetime64[ns](1), float64(2), object(11)
memory usage: 66.6+ KB

In [62]:
#Info faltante

# Campos que queremos revisar si les falta información
campos_objetivo = ['hora', 'promotor', 'direccion', 'codigo_postal']

# Filtrar filas donde al menos uno de esos campos tenga valor nulo
faltantes = data_ticketmaster[data_ticketmaster[campos_objetivo].isnull().any(axis=1)]

# Seleccionar las columnas útiles para buscar información
faltantes = faltantes[['id_evento', 'nombre', 'lugar'] + campos_objetivo]

# Mostrar los resultados
print("🎯 Eventos con información faltante:\n")
print(faltantes)

🎯 Eventos con información faltante:

               id_evento                                             nombre  \
15     Z698xZ2qZ1kvpvMFK                                               HVOB
33         Z7r9jZ1A7bK0K                                     Counting Crows
42    Z698xZ2qZ16v8w0kok                 Author & Punisher - Barcelona 2025
66   Zo98xZ2qZp_76AFZrrr                                        Sam Garrett
70     Z698xZ2qZ1kJp-voV                       Carlos Escobedo + Romanthica
..                   ...                                                ...
456    Z698xZ2qZ1k1d4-Ja  LINKIN PARK: From Zero World Tour 2026 | VIP P...
463   Z698xZ2qZ16eZg4x_3                                         Baron Rojo
487    Z698xZ2qZ1kaPbaup                          MARTÍN - naTOURaleza 2025
508   Z698xZ2qZ16eZoo_xa  ABONOS - Temporada 2025/2026 - Azulmarino Balo...
509    Z698xZ2qZ1kFvOy3K                             Palmer Basket Mallorca

                                lugar      hora                    promotor  \
15                         Sala Apolo       NaN         Sergio Solís Gálvez
33                         Razzmatazz  20:30:00                         NaN
42                               WOLF       NaN         Sergio Solís Gálvez
66                  Sala Razzmatazz 1  19:00:00                         NaN
70       Sala Upload - Poble Espanyol       NaN         Sergio Solís Gálvez
..                                ...       ...                         ...
456             Auditorio Miguel Ríos       NaN       Dalt Vila Music, S.L.
463                     Sala París 15       NaN         Rubén Rosas Sánchez
487                       El Volander  22:30:00         Planet Events, S.A.
508  Palau Municipal Esports Son Moix       NaN  Fundación Bàsquet Mallorca
509  Palau Municipal Esports Son Moix       NaN               Palmer Basket

                            direccion  codigo_postal
15           C. Nou de la Rambla, 113           8004
33                    C/ Pamplona, 88           8018
42         Carrer dels Almogàvers, 88           8018
66                 C. Almogàvers, 122           8018
70   Av Francesc Ferrer i Guardia, 13           8100
..                                ...            ...
456           Pso. Alicia Alonso, s/n          28521
463           Calle de la Orotava, 27          29006
487        Carrer Navarro Cabanes, 25           <NA>
508             Camí de la Vileta, 40           7011
509             Camí de la Vileta, 40           7011

[109 rows x 7 columns]

In [64]:
# Guardar el nuevo data
data_ticketmaster.to_csv("data_ticketmaster.csv", index=False, encoding="utf-8")
print("✅ Archivo guardado como data_ticketmaster.csv")

✅ Archivo guardado como data_ticketmaster.csv

### TRANSFORMACIÓN Y LIMPIEZA

In [66]:
import re

In [71]:

# 1) Cargar archivo original
df = pd.read_csv("data_ticketmaster.csv")

# 2) Función para limpiar texto
def clean_text(s):
    if pd.isna(s):
        return ""
    s = str(s)
    # Mantener letras, números, puntuación básica y acentos
    s = re.sub(r"[^\w\s.,;:!?()\-\'\"áéíóúüñÁÉÍÓÚÜÑ/@&]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()  # quitar espacios múltiples
    return s

# 3) Definir clasificación de experiencia
def classify_experience(row):
    tipo = str(row.get("tipo_evento", "") or "").lower()
    genero = str(row.get("genero", "") or "").lower()
    subgenero = str(row.get("subgenero", "") or "").lower()
    nombre = str(row.get("nombre", "") or "").lower()

    if "sport" in tipo or "deporte" in tipo:
        return "Deporte"
    if "music" in tipo or "música" in tipo or "musica" in tipo:
        return "Vida nocturna"
    if "arts" in tipo or "theatre" in tipo or "teatro" in tipo or "cultura" in tipo:
        return "Cultura"
    if "film" in tipo or "cine" in tipo:
        return "Cultura"
    if "family" in tipo or "kids" in tipo or "familiar" in tipo:
        return "Ocio"

    # Fallbacks con palabras clave
    texto_busqueda = genero + " " + subgenero + " " + nombre
    if any(k in texto_busqueda for k in ["fútbol", "futbol", "basket", "baloncesto", "tenis", "carrera", "maratón", "maraton"]):
        return "Deporte"
    if any(k in texto_busqueda for k in ["concierto", "dj", "festival", "rock", "pop", "reggaeton", "rap", "techno", "electrónica", "electronica", "club"]):
        return "Vida nocturna"
    if any(k in texto_busqueda for k in ["exposición", "exposicion", "museo", "galería", "galeria"]):
        return "Museo"
    if any(k in texto_busqueda for k in ["teatro", "ópera", "opera", "ballet", "danza", "comedia", "circo"]):
        return "Cultura"
    if any(k in texto_busqueda for k in ["tour", "visita", "ruta", "excursión", "excursion"]):
        return "Tour"
    if any(k in texto_busqueda for k in ["restaurante", "gastron", "tapas", "food", "comida", "vino", "cata"]):
        return "Comida"
    if any(k in texto_busqueda for k in ["playa", "beach", "chiringuito"]):
        return "Playa"
    if any(k in texto_busqueda for k in ["hotel", "resort", "spa"]):
        return "Hotel"

    return "Desconocido"

# 4) Crear nuevo DataFrame con columnas finales
data_ticketmaster = pd.DataFrame({
    "texto": df["nombre"].map(clean_text),
    "ciudad": df["ciudad_buscada"].fillna("").astype(str).str.strip(),
    "experiencia": df.apply(classify_experience, axis=1),
    "fecha": pd.to_datetime(df["fecha"], errors="coerce").dt.date,
    "fuente": "Ticketmaster"
})

# 🔄 Normalizar nombres de ciudades
reemplazos_ciudad = {
    "Palma de Mallorca": "Mallorca",
    "Santa Cruz de Tenerife": "Tenerife",
    "Las Palmas de Gran Canaria": "Gran Canaria"
}
data_ticketmaster["ciudad"] = data_ticketmaster["ciudad"].replace(reemplazos_ciudad)

# 5) Guardar resultado
data_ticketmaster.to_csv("ticketmaster_final.csv", index=False, encoding="utf-8")

print("✅ Archivo guardado como ticketmaster_final.csv")
print(data_ticketmaster.head())
print("\n📊 Conteo por ciudad normalizada:")
print(data_ticketmaster["ciudad"].value_counts())

✅ Archivo guardado como ticketmaster_final.csv
                                               texto     ciudad  \
0            Fito & Fitipaldis - Aullidos Tour 25/26   Tenerife
1                                MVRK: Pórtate bien!   Tenerife
2  Lauren Spencer Smith - THE ART OF BEING A MESS...  Barcelona
3  Lauren Spencer Smith - THE ART OF BEING A MESS...  Barcelona
4         Neo Pistea - Culto Tour Internacional 2025  Barcelona

     experiencia       fecha        fuente
0  Vida nocturna  2026-03-14  Ticketmaster
1  Vida nocturna  2025-11-28  Ticketmaster
2  Vida nocturna  2025-09-04  Ticketmaster
3  Vida nocturna  2025-09-04  Ticketmaster
4  Vida nocturna  2025-09-04  Ticketmaster

📊 Conteo por ciudad normalizada:
ciudad
Madrid          297
Barcelona       149
Valencia         22
Sevilla          14
Malaga            9
Mallorca          4
Tenerife          2
Gran Canaria      1
Name: count, dtype: int64